apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: default
type: Opaque
stringData:
  NODE_ENV: production
  PORT: "3000"

  FRONTEND_URL: http://frontend-service.default.svc.cluster.local:80

  DB_HOST: MySqlFlexibleServer_7731551d5db84b36a0367b28a1062237.mysql.database.azure.com
  DB_USER: adminmysql@MySqlFlexibleServer_7731551d5db84b36a0367b28a1062237
  DB_PASSWORD: Gymdb1234
  DB_NAME: mydb

  DB_CONNECTION_LIMIT: "10"
  DB_QUEUE_LIMIT: "0"

  ALLOWED_METHODS: GET,POST,PUT,DELETE,PATCH
  ALLOWED_HEADERS: Content-Type,Authorization
---
apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
  namespace: default
type: Opaque
stringData:
  VITE_API_BASE_URL: http://backend-service.default.svc.cluster.local:3000
  VITE_API_TIMEOUT: "10000"
  VITE_APP_ENV: production
  VITE_APP_VERSION: "1.0.0"
  VITE_FEATURE_PAYMENTS_ENABLED: "true"
  VITE_FEATURE_REPORTS_ENABLED: "false"
